### ISSUE TITLE
Doesn't work on real hardware

### ISSUE THREAD

**Issue by animekai** [headshot2017/supertux-dc#1]
Supertux works on emulators but no in a real dreamcast, it freezes on loading... screen maybe due to low ram on real hardware, maybe.

**Comment by headshot2017** [comment]
the game works on the current master branch in real hardware (the v0.1.1 release doesn't, but i didn't know at the time). there's only the problem of big sound delays which it's the last thing i must look into, and that will be released as v0.1.1a

**Comment by headshot2017** [comment]
v0.1.1a is out, have a look

**Comment by animekai** [comment]
> v0.1.1a is out, have a look

I will, and I comment if works

**Comment by headshot2017** [comment]
did it work? if it did you can close this issue

**Comment by ianmicheal** [comment]
It works perfect on hardware now..

**Comment by ianmicheal** [comment]
> > v0.1.1a is out, have a look
> 
> I will, and I comment if works

It works correct now :)

**Comment by animekai** [comment]
yes now is working on a real dreamcast, thanks.
